CREATE TABLE paths (
  path_id SERIAL PRIMARY KEY,
  driver_id INT NOT NULL,
  car_id INT NOT NULL,
  start_location VARCHAR(255) NOT NULL,
  end_location VARCHAR(255) NOT NULL,
  arrival_time TIMESTAMP NOT NULL,
  departure_time TIMESTAMP NOT NULL,
  distance FLOAT NOT NULL,
  estimated_time FLOAT NOT NULL,
  available_seats INT NOT NULL,
  start_lat FLOAT NOT NULL,
  start_lng FLOAT NOT NULL,
  end_lat FLOAT NOT NULL,
  end_lng FLOAT NOT NULL,
  path_data JSONB NOT NULL,
  stops JSONB,
  passanges JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (driver_id) REFERENCES drivers(driver_id) ON DELETE CASCADE,
  FOREIGN KEY (car_id) REFERENCES cars(car_id) ON DELETE CASCADE
);
